# Generated by Django 4.0.4 on 2023-03-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_table_1_table_2_table_3_table_4_table_5_table_6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_1',
            name='title_of_table',
        ),
        migrations.AlterField(
            model_name='table_2',
            name='author_type',
            field=models.CharField(max_length=300, verbose_name='Тип автора'),
        ),
        migrations.AlterField(
            model_name='table_2',
            name='co_creators',
            field=models.CharField(max_length=300, verbose_name='Соавторы'),
        ),
        migrations.AlterField(
            model_name='table_2',
            name='journal_title',
            field=models.CharField(max_length=300, verbose_name='Название журнала, номер, год выпуска '),
        ),
        migrations.AlterField(
            model_name='table_2',
            name='number_of_authors',
            field=models.CharField(max_length=300, verbose_name='Количество авторов'),
        ),
        migrations.AlterField(
            model_name='table_2',
            name='rinc',
            field=models.CharField(max_length=300, verbose_name='Наличие статьи в базах РИНЦ'),
        ),
        migrations.AlterField(
            model_name='table_2',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='table_2',
            name='title_of_table',
            field=models.CharField(max_length=300, verbose_name='Журналы входящие в Рецензирумые зарубежные журналы (РИНЦ)'),
        ),
        migrations.AlterField(
            model_name='table_3',
            name='author_type',
            field=models.CharField(max_length=300, verbose_name='Тип автора'),
        ),
        migrations.AlterField(
            model_name='table_3',
            name='co_creators',
            field=models.CharField(max_length=300, verbose_name='Соавторы'),
        ),
        migrations.AlterField(
            model_name='table_3',
            name='journal_title',
            field=models.CharField(max_length=300, verbose_name='Название журнала, номер, год выпуска '),
        ),
        migrations.AlterField(
            model_name='table_3',
            name='kokson',
            field=models.CharField(max_length=300, verbose_name='Наличие статьи в перечне,  рекомендуемые КОКСНВО РК '),
        ),
        migrations.AlterField(
            model_name='table_3',
            name='number_of_authors',
            field=models.CharField(max_length=300, verbose_name='Количество авторов'),
        ),
        migrations.AlterField(
            model_name='table_3',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='table_3',
            name='title_of_table',
            field=models.CharField(max_length=300, verbose_name='Журналы входящие в Рецензирумые зарубежные журналы рекомендуемые КОКСНВО'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='author_type',
            field=models.CharField(max_length=300, verbose_name='Тип автора'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='co_creators',
            field=models.CharField(max_length=300, verbose_name='Соавторы'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='conf',
            field=models.CharField(max_length=300, verbose_name='конференции международные,республиканские(название сборника, месяц, год)'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='int',
            field=models.CharField(max_length=300, verbose_name='международные,республиканские'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='journal_title',
            field=models.CharField(max_length=300, verbose_name='Название журнала, номер, год выпуска '),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='number_of_authors',
            field=models.CharField(max_length=300, verbose_name='Количество авторов'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='table_4',
            name='title_of_table',
            field=models.CharField(max_length=300, verbose_name='Статьи опубликованные в сборниках конференции'),
        ),
        migrations.AlterField(
            model_name='table_5',
            name='author_type',
            field=models.CharField(max_length=300, verbose_name='Тип автора'),
        ),
        migrations.AlterField(
            model_name='table_5',
            name='authors',
            field=models.CharField(max_length=300, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='table_5',
            name='data',
            field=models.CharField(max_length=300, verbose_name='Данные о свидетельстве (номер, дата, год)'),
        ),
        migrations.AlterField(
            model_name='table_5',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название Свидетельства'),
        ),
        migrations.AlterField(
            model_name='table_5',
            name='title_of_table',
            field=models.CharField(max_length=300, verbose_name='Свидетельство о государственной регистрации прав на объект авторского права'),
        ),
        migrations.AlterField(
            model_name='table_6',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название проекта ИРН'),
        ),
        migrations.AlterField(
            model_name='table_6',
            name='title2',
            field=models.CharField(max_length=300, verbose_name='Запрашиваемая Сумма '),
        ),
        migrations.AlterField(
            model_name='table_6',
            name='title3',
            field=models.CharField(max_length=300, verbose_name='Период участия в проекте'),
        ),
        migrations.AlterField(
            model_name='table_6',
            name='title4',
            field=models.CharField(max_length=300, verbose_name='Участие в проектах в рамках программно-целевого финансирования'),
        ),
        migrations.AlterField(
            model_name='table_6',
            name='title5',
            field=models.CharField(max_length=300, verbose_name='Участие в проектах в рамках  грантового финансирования'),
        ),
        migrations.AlterField(
            model_name='table_6',
            name='title6',
            field=models.CharField(max_length=300, verbose_name='Участие в международных научно-исследовательских проектах / программах  '),
        ),
        migrations.AlterField(
            model_name='table_6',
            name='title7',
            field=models.CharField(max_length=300, verbose_name='Участия в проектах по коммерциализации, внедрению ипродвижению научных результатов,финансируемых из '),
        ),
        migrations.AlterField(
            model_name='table_6',
            name='title_of_table',
            field=models.CharField(max_length=300, verbose_name='Участие в научных проектах '),
        ),
    ]
