# Generated by Django 4.0.4 on 2023-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_remove_table_1_title_of_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_1',
            name='url',
            field=models.CharField(max_length=100, verbose_name='DOI статьи'),
        ),
    ]
