# Generated by Django 4.0.4 on 2023-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
